const movies = [
  {
    id: 1,
    title: "Juzni Vetar",
    year: 2018,
    image: "/thumbnails/movies/juzni_vetar.webp",
    trailerUrl: "VD6d7_xEAq4",
    imdbUrl: "https://www.imdb.com/title/tt10952900/",
    popular: true,
    newRelease: false,
    recommendation: false,
    genre: ["Crime", "Thriller", "Comedy"],
    description:
      "Belgrade-based Peter Maras, who works for a criminal syndicate, jeopardises the safety of his family members when he goes against a notorious criminal mastermind.",
    director: ["Miloš Avramović"],
    writers: ["Miloš Avramović", "Petar Mihajlović"],
    cast: ["Miloš Biković", "Miodrag Radonjić", "Predrag 'Miki' Manojlović", "Toni Mihajlovski"],
    producers: ["Miloš Avramović", "Tatjana Zeželj Gojković", "Miodrag Radonjić"],
    cinematography: ["Ivan Kostić"],
    editing: ["Milena Predić", "Lazar Predojev"],
    costume: ["Jelena Đorđević"],
  },
  {
    id: 2,
    title: "Balkankan",
    year: 2005,
    image: "/thumbnails/movies/balkankan.webp",
    trailerUrl: "Ov7tyctn1wg",
    imdbUrl: "https://www.imdb.com/title/tt0369258/",
    popular: true,
    newRelease: true,
    recommendation: true,
    genre: ["Action", "Comedy"],
    description:
      "Robbers Serafim and Vitomir are caught by an underworld gangster. A guilty Vitomir escapes to Italy, but years later, his son promises to help Serafim's family.",
    director: ["Darko Mitrevski"],
    writers: ["Darko Mitrevski"],
    cast: ["Vlado Jovanovski", "Adolfo Margiotta", "Zvezda Angelovska", "Toni Mihajlovski"],
    producers: ["Darko Mitrevski", "Alessandro Verdecchi", "Gianluca Curti"],
    cinematography: ["Suki Medencević"],
    editing: ["Giacobbe Gamberini"],
    costume: ["Information not publicly available"],
  },
  {
    id: 3,
    title: "Zona Zamfirova",
    year: 2002,
    image: "/thumbnails/movies/zona_zamfirova.webp",
    trailerUrl: "k4LARxZv9to",
    imdbUrl: "https://www.imdb.com/title/tt3429340/",
    popular: true,
    newRelease: false,
    recommendation: true,
    genre: ["Drama", "Drama"],
    description:
      "Zona, a rich man's daughter, is in love with Mane, an ordinary goldsmith. As it is objectionable for a rich girl to marry a poor man, the two get separated. Mane makes a plan to marry Zona.",
    director: ["Zdravko Šotra"],
    writers: ["Stevan Sremac"],
    cast: ["Katarina Radivojević", "Vojin Ćetković", "Dragan Nikolić", "Toni Mihajlovski"],
    producers: ["Miroslav Mitić"],
    cinematography: ["Veselko Krčmar"],
    editing: ["Petar Putniković"],
    costume: ["Information not publicly available"],
  },
  {
    id: 4,
    title: "Treto poluvreme",
    year: 2012,
    image: "/thumbnails/movies/third_half.webp",
    trailerUrl: "dy-yuONtn4A",
    imdbUrl: "https://www.imdb.com/title/tt2069100/",
    popular: true,
    newRelease: false,
    recommendation: true,
    genre: ["Sport", "War"],
    description:
      "A footballer playing for the Macedonian Football Club falls in love with a Jewish woman. But their happiness is threatened by the new Nazi government, who are also gunning for the club's Jewish coach.",
    director: ["Darko Mitrevski"],
    writers: ["Darko Mitrevski", "Grgur Strujic"],
    cast: ["Katarina Ivanovska", "Sasko Kocev", "Richard Sammel", "Toni Mihajlovski"],
    producers: ["Darko Mitrevski", "Robert Naskov", "Milivoje Gorgevic"],
    cinematography: ["Klaus Fuxjäger"],
    editing: ["Dejan Boskovic", "Alois Fisárek"],
    costume: ["Zaklina Krstevska", "Ksenija Terzovic"],
  },
  {
    id: 5,
    title: "Iluzija",
    year: 2004,
    image: "/thumbnails/movies/mirage.webp",
    trailerUrl: "OBRw9MZU2yw",
    imdbUrl: "https://www.imdb.com/title/tt0368962/",
    popular: false,
    newRelease: true,
    recommendation: true,
    genre: ["Drama"],
    description:
      "Marko, a poet, gets fed up with the constant abuse from his friends and family and decides to escape into an imaginary world of his own where everything is perfect.",
    director: ["Svetozar Ristovski"],
    writers: ["Svetozar Ristovski", "Grace Lea Troje"],
    cast: ["Marko Kovačević", "Vlado Jovanovski", "Mustafa Nadarević"],
    producers: ["Svetozar Ristovski", "Harold Lee Tichenor"],
    cinematography: ["Vladimir Samoilovski"],
    editing: ["Atanas Georgiev"],
    costume: ["Information not publicly available"],
  },
  {
    id: 6,
    title: "Honeyland",
    year: 2019,
    image: "/thumbnails/movies/honeyland.webp",
    trailerUrl: "B27ORUHlp6E",
    imdbUrl: "https://www.imdb.com/title/tt8991268/",
    popular: true,
    newRelease: false,
    recommendation: true,
    genre: ["Documentary", "Drama"],
    description:
      "A woman utilises ancient beekeeping traditions to cultivate honey in the mountains of North Macedonia. When a neighbouring family tries to do the same, it becomes a source of tension as they disregard her wisdom and advice.",
    director: ["Tamara Kotevska", "Ljubomir Stefanov"],
    writers: ["Tamara Kotevska", "Ljubomir Stefanov"],
    cast: ["Hatidže Muratova", "Nazife Muratova", "Hussein Sam", "Toni Mihajlovski"],
    producers: ["Atanas Georgiev"],
    cinematography: ["Fejmi Daut", "Samir Ljuma"],
    editing: ["Atanas Georgiev"],
    costume: ["Information not publicly available"],
  },
  {
    id: 7,
    title: "Lazar",
    year: 2015,
    image: "/thumbnails/movies/lazar.webp",
    trailerUrl: "ZMiVMaeK-w4",
    imdbUrl: "https://www.imdb.com/title/tt2925388/",
    popular: true,
    newRelease: false,
    recommendation: true,
    genre: ["Thriller", "Crime"],
    description:
      "Involved in a ring of illegal smugglers, Lazar lives a disconnected life until he meets Katerina, with whom he envisions a hopeful future. But leaving the criminal world is harder than he imagined.",
    director: ["Svetozar Ristovski"],
    writers: ["Svetozar Ristovski", "Grgur Strujic"],
    cast: ["Vedran Živolić", "Dejan Lilikj", "Nataša Petrović", "Toni Mihajlovski"],
    producers: ["Svetozar Ristovski", "Robert Naskov", "Milivoje Gorgevic"],
    cinematography: ["Klaus Fuxjäger"],
    editing: ["Dejan Boskovic", "Alois Fisárek"],
    costume: ["Zaklina Krstevska", "Ksenija Terzovic"],
  },
  {
    id: 8,
    title: "To the Hilt",
    year: 2014,
    image: "/thumbnails/movies/do_balcak.webp",
    trailerUrl: "35q1sKuUypw",
    imdbUrl: "https://www.imdb.com/title/tt2396459/",
    popular: true,
    newRelease: false,
    recommendation: false,
    genre: ["Action", "Adventure"],
    description:
      "An open-minded European woman flirts with three men and puts them through a series of tasks and events which turn out to have serious consequences.",
    director: ["Stole Popov"],
    writers: ["Stole Popov", "Goran Stefanovski"],
    cast: ["Inti Sraj", "Sasko Kocev", "Martin Jordanovski"],
    producers: ["Jordančo Čevrevski", "Vladimir Anastasov", "Milivoje Gorgevic"],
    cinematography: ["Apostol Trpeski"],
    editing: ["Atanas Georigev", "Blagoja Nedelkovski"],
    costume: ["Emilija I. Atanasovska", "Svetlana Gutikj"],
  },
  {
    id: 9,
    title: "The Balkan Line",
    year: 2019,
    image: "/thumbnails/movies/balkanska_medja.webp",
    trailerUrl: "Ih-cpE1Fxuw",
    imdbUrl: "https://www.imdb.com/title/tt5951188/",
    popular: false,
    newRelease: true,
    recommendation: false,
    genre: ["Action", "Drama", "War"],
    description:
      "A Russian task force, led by Andrei Shatalov, is dispatched to recapture the Slatina Air Base in Kosovo and defend it until reinforcements arrive.",
    director: ["Andrei Kavun"],
    writers: ["Andrei Kavun", "Andrei Shcherbakov"],
    cast: ["Gosha Kutsenko", "Emir Kusturica", "Igor Gordin"],
    producers: ["Fyodor Bondarchuk", "Andrei Kavun", "Leonid Vereshchagin"],
    cinematography: ["Sergey Trofimov"],
    editing: ["Aleksey Bobrov"],
    costume: ["Yelena Moskvina"],
  },
  {
    id: 10,
    title: "Ambulance",
    year: 2022,
    image: "/thumbnails/movies/ambulance.webp",
    trailerUrl: "7NU-STboFeI",
    imdbUrl: "https://www.imdb.com/title/tt4998632/",
    popular: true,
    newRelease: false,
    recommendation: true,
    genre: ["Action", "Thriller", "Heist"],
    description:
      "Needing money to cover his wife's medical bills, a decorated veteran teams up with his adoptive brother to steal $32 million from a Los Angeles bank.",
    director: ["Michael Bay"],
    writers: ["Chris Fedak", "Laurits Munch-Petersen", "Lars Andreas Pedersen"],
    cast: ["Jake Gyllenhaal", "Yahya Abdul-Mateen II", "Eiza González"],
    producers: ["Michael Bay", "Bradley J. Fischer", "James Vanderbilt"],
    cinematography: ["Roberto De Angelis"],
    editing: ["Pietro Scalia", "Doug Brandt", "Calvin Wimmer"],
    costume: ["Lisa Nora Lovaas"],
  },
  {
    id: 11,
    title: "Only Human",
    year: 2020,
    image: "/thumbnails/movies/only_human.webp",
    trailerUrl: "AdjEpNlqog8",
    imdbUrl: "https://www.imdb.com/title/tt10230576/",
    popular: false,
    newRelease: true,
    recommendation: false,
    genre: ["Drama"],
    description:
      "What is Man? Homo shows six faces, six phases in cleverly- connected, blackly comic episodes as desperate characters meet unwittingly in a modern metropole in the eternal search for the means to survive.",
    director: ["Igor Ivanov Izi"],
    writers: ["Igor Ivanov Izi", "Sasho Kokalanov"],
    cast: ["Natasha Petrovic", "Igor Angelov", "Oliver Mitkovski"],
    producers: ["Tomi Salkovski", "Lumbardh Kukaj", "Bojan Mastilovic"],
    cinematography: ["Maja Radosevic"],
    editing: ["Martin Ivanov"],
    costume: ["Kiril Spaseski", "Polona Valentincic"],
  },
  {
    id: 12,
    title: "The Liberation of Skopje",
    year: 2016,
    image: "/thumbnails/movies/liberation_skopje.webp",
    trailerUrl: "YZq8o_U8vxo",
    imdbUrl: "https://www.imdb.com/title/tt4168286/",
    popular: true,
    newRelease: false,
    recommendation: true,
    genre: ["Drama", "War"],
    description:
      "During WWII, a young boy, Zoran, witnesses the horrors and atrocities in German-occupied Skopje. At the same time, his father is fighting the partisans and his mother falls in love with a German.",
    director: ["Rade Šerbedžija", "Danilo Šerbedžija"],
    writers: ["Dušan Jovanović", "Rade Šerbedžija"],
    cast: ["Rade Šerbedžija", "Lucija Šerbedžija", "Silvija Stojanovska"],
    producers: ["Igor Nola", "Robert Naskov", "Goran Tozija"],
    cinematography: ["Dejan Dimeski"],
    editing: ["Nicolas Gaster"],
    costume: ["Željka Franulović"],
  },
  {
    id: 13,
    title: "Bistra Voda",
    year: 2023,
    image: "/thumbnails/movies/bistra_voda.webp",
    trailerUrl: "NSiyn8t-4x0",
    imdbUrl: "https://www.imdb.com/title/tt21241730/",
    popular: false,
    newRelease: true,
    recommendation: true,
    genre: ["Drama", "Thriller"],
    description:
      "Bistra Voda is a Macedonian television series that delves into the complexities of identity, betrayal, and the consequences of political choices.",
    director: ["Jani Bojadži"],
    writers: ["Jani Bojadži", "Mona Paskalova"],
    cast: ["Simeon Moni Damevski", "Keti Doncevska-Ilić", "Meto Jovanovski", "Toni Mihajlovski"],
    producers: ["Jani Bojadži", "Dejan Miloševski"],
    cinematography: ["Kristijan Karadžovski", "Marjan Petkovski"],
    editing: ["Blaže Dulev", "David Dulev"],
    costume: ["Marija Dimishkoska", "Nela Todorovska"],
  },
  {
    id: 14,
    title: "Makedonska krvava svadba",
    year: 1967,
    image: "/thumbnails/movies/krvava_svadba.webp",
    trailerUrl: "Ov7tyctn1wg",
    imdbUrl: "https://www.imdb.com/title/tt0179957/",
    popular: true,
    newRelease: false,
    recommendation: true,
    genre: ["History", "Drama"],
    description:
      "A girl named Cveta is abducted by the Ottoman Empire and forced into embracing Islam.",
    director: ["Trajče Popov"],
    writers: ["Voydan Chernodrinski"],
    cast: ["Risto Šiškov", "Vera Čukić", "Zafer Hadžimano", "Toni Mihajlovski"],
    producers: ["Branko Popčevski", "Vardar Film"],
    cinematography: ["Kiro Bilbilovski"],
    editing: ["Vangel 'Laki' Čemčev"],
    costume: ["Nikola Lazarevski"],
  },
  {
    id: 15,
    title: "Senki",
    year: 2007,
    image: "/thumbnails/movies/senki.webp",
    trailerUrl: "HJl2Qpfeg1o",
    imdbUrl: "https://www.imdb.com/title/tt0834102/",
    popular: false,
    newRelease: true,
    recommendation: false,
    genre: ["Drama", "Horror", "Mystery", "Thriller"],
    description:
      "A horrendous car-crash puts a young doctor in contact with the souls of the dead. The spirits have an important message and in order to meet their demands, he will have to look within.",
    director: ["Milcho Manchevski"],
    writers: ["Milcho Manchevski"],
    cast: ["Borce Nacev", "Vesna Stanojevska", "Sabina Ajrula-Tozija"],
    producers: ["Milcho Manchevski", "Amedeo Pagani", "Corinna Mehner"],
    cinematography: ["Fabio Cianchetti"],
    editing: ["David Ray", "Martin Levenstein"],
    costume: ["Information not publicly available"],
  },
  {
    id: 16,
    title: "Sisterhood",
    year: 2021,
    image: "/thumbnails/movies/sisterhood.webp",
    trailerUrl: "i2eNmrtLUCk",
    imdbUrl: "https://www.imdb.com/title/tt14953090/",
    popular: false,
    newRelease: true,
    recommendation: false,
    genre: ["Drama"],
    description:
      "The friendship between two teenage girls turns toxic after they post a classmate's intimate video online. The classmate goes missing, and the girls face dire repercussions.",
    director: ["Dina Duma"],
    writers: ["Dina Duma", "Martin Ivanov"],
    cast: ["Antonija Belazelkoska", "Mia Giraud", "Marija Jančevska"],
    producers: ["Marija Dimitrova"],
    cinematography: ["Naum Doksevski"],
    editing: ["Martin Ivanov"],
    costume: ["Information not publicly available"],
  },
];

exports.handler = async (event, context) => {
  const path = event.path.replace('/.netlify/functions/movies', '');
  const method = event.httpMethod;

  // Handle GET /api/movies/:id
  if (method === 'GET' && path && path !== '/') {
    const movieId = parseInt(path.substring(1)); // Remove leading slash
    const movie = movies.find((m) => m.id === movieId);

    if (movie) {
      return {
        statusCode: 200,
        headers: {
          'Access-Control-Allow-Origin': '*',
          'Access-Control-Allow-Headers': 'Content-Type',
          'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
        },
        body: JSON.stringify(movie),
      };
    } else {
      return {
        statusCode: 404,
        headers: {
          'Access-Control-Allow-Origin': '*',
          'Access-Control-Allow-Headers': 'Content-Type',
          'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
        },
        body: JSON.stringify({ message: "Movie not found" }),
      };
    }
  }

  // Handle GET /api/movies
  if (method === 'GET') {
    return {
      statusCode: 200,
      headers: {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Headers': 'Content-Type',
        'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
      },
      body: JSON.stringify(movies),
    };
  }

  // Handle OPTIONS for CORS
  if (method === 'OPTIONS') {
    return {
      statusCode: 200,
      headers: {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Headers': 'Content-Type',
        'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
      },
      body: '',
    };
  }

  return {
    statusCode: 405,
    headers: {
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Headers': 'Content-Type',
      'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
    },
    body: JSON.stringify({ message: "Method not allowed" }),
  };
};
